- 👋 Hi, I’m @SelahattinEmir01 / Selahattin Emir Demir
- 👀 I’m interested in encode and games
- 🔞 I'm 13 years old 
- 🎉 I was born in 2008
- 🌱 I’m currently learning how to code or desinging website
- 💞️ I’m looking to collaborate on website desinger
- 📫 How to reach me (werkings001@gmail.com)
